### ISSUE TITLE
Add a tracker to bank_history for purchases

### ISSUE THREAD

**Issue by uaktags** [OpenThrone/OpenThrone#76]
- [x] Add a new column to bank_history for a JSON? field, we'll store data relevant to the transaction here
- [x] Everytime we buy/sell/train/untrain add a new record to bank_history for the tx
- [x] Keep track of how much of what was bought/sold
- [x] Include starting value, and ending values into the new stats field. Later we can remove this but its best for debugging.

**Comment by MarkTraceur** [comment]
>  Everytime we buy/sell/train/untrain add a new record to bank_history for the tx

Is this done now? From my review of #197 it seemed like we're saving this information now.
